# Generated by Django 5.0 on 2024-07-14 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('set', models.CharField(max_length=255)),
                ('template', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'signatures',
            },
        ),
        migrations.CreateModel(
            name='Statements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('folder_name1', models.CharField(max_length=100)),
                ('folder_name2', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=100)),
                ('template_json', models.JSONField()),
                ('type', models.CharField(max_length=100)),
                ('doc_count', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'statements',
                'unique_together': {('folder_name1', 'folder_name2', 'file_name')},
            },
        ),
        migrations.CreateModel(
            name='StatementLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('folder_name1', models.CharField(max_length=100)),
                ('folder_name2', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=100)),
                ('template_json', models.JSONField()),
                ('doc_count', models.SmallIntegerField()),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statements.statements')),
            ],
            options={
                'db_table': 'statements_logs',
            },
        ),
        migrations.CreateModel(
            name='WodaDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('folder_name1', models.CharField(max_length=100)),
                ('folder_name2', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=100)),
                ('template_json', models.JSONField()),
                ('type', models.CharField(max_length=100)),
                ('doc_count', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'woda_docs',
                'unique_together': {('folder_name1', 'folder_name2', 'file_name')},
            },
        ),
        migrations.CreateModel(
            name='WodaLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('folder_name1', models.CharField(max_length=100)),
                ('folder_name2', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=100)),
                ('template_json', models.JSONField()),
                ('doc_count', models.CharField(max_length=100)),
                ('wodadoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statements.wodadocs')),
            ],
            options={
                'db_table': 'wodadocs_logs',
            },
        ),
    ]
