# Generated by Django 5.0.7 on 2024-07-23 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('set', models.CharField(max_length=255)),
                ('template', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'signatures',
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='statements.folder')),
            ],
            options={
                'db_table': 'folder',
            },
        ),
        migrations.CreateModel(
            name='Statements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('template', models.JSONField()),
                ('type', models.CharField(max_length=100)),
                ('bank', models.CharField(max_length=100)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statements.folder')),
            ],
            options={
                'db_table': 'statements',
                'unique_together': {('folder', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StatementLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('template', models.JSONField()),
                ('type', models.CharField(max_length=100)),
                ('bank', models.CharField(max_length=100)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statements.folder')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statements.statements')),
            ],
            options={
                'db_table': 'statements_logs',
            },
        ),
        migrations.CreateModel(
            name='WodaDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('template', models.JSONField()),
                ('type', models.CharField(max_length=100)),
                ('municipality', models.CharField(max_length=100)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statements.folder')),
            ],
            options={
                'db_table': 'woda_docs',
                'unique_together': {('folder', 'name')},
            },
        ),
        migrations.CreateModel(
            name='WodaLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('template', models.JSONField()),
                ('type', models.CharField(max_length=100)),
                ('municipality', models.CharField(max_length=100)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statements.folder')),
                ('wodadoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statements.wodadocs')),
            ],
            options={
                'db_table': 'wodadocs_logs',
            },
        ),
    ]
