# Generated by Django 5.0 on 2024-07-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statements',
            name='bank',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wodadocs',
            name='municipality',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
