# Generated by Django 5.0.7 on 2024-07-23 10:56

from django.db import migrations

def populate_data(apps, schema_editor):
    Folder = apps.get_model('statements','Folder')

    Folder.objects.bulk_create([
        Folder(code='1',name='Statement Documents',parent=None),
        Folder(code='2', name='Woda Documents', parent=None)
    ])


def revert_data(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_data, revert_data),
    ]
