# Generated by Django 5.0 on 2024-07-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wodadocs',
            name='doc_count',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
