# Generated by Django 5.0 on 2024-07-18 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0002_statements_bank_wodadocs_municipality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statements',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='wodadocs',
            name='municipality',
        ),
    ]
