# Generated by Django 5.0.7 on 2024-07-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0002_auto_20240723_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=255, unique=True),
        ),
    ]
