# Generated by Django 5.0 on 2024-07-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0002_wodadocs_doc_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statementlogs',
            old_name='folder_name',
            new_name='folder_name1',
        ),
        migrations.RenameField(
            model_name='statements',
            old_name='folder_name',
            new_name='folder_name1',
        ),
        migrations.RenameField(
            model_name='wodadocs',
            old_name='folder_name',
            new_name='folder_name1',
        ),
        migrations.RenameField(
            model_name='wodalogs',
            old_name='folder_name',
            new_name='folder_name1',
        ),
        migrations.AlterUniqueTogether(
            name='statements',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='wodadocs',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='statementlogs',
            name='folder_name2',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statements',
            name='folder_name2',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wodadocs',
            name='folder_name2',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wodalogs',
            name='folder_name2',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='statements',
            unique_together={('folder_name1', 'folder_name2', 'file_name')},
        ),
        migrations.AlterUniqueTogether(
            name='wodadocs',
            unique_together={('folder_name1', 'folder_name2', 'file_name')},
        ),
    ]
