# Generated by Django 5.0.7 on 2024-07-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0003_alter_folder_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signatures',
            name='value',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterUniqueTogether(
            name='signatures',
            unique_together={('template', 'value')},
        ),
    ]
