# Generated by Django 5.0 on 2024-07-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0003_rename_folder_name_statementlogs_folder_name1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wodalogs',
            name='doc_count',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
