# Generated by Django 5.0 on 2024-07-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0004_wodalogs_doc_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('set', models.CharField(max_length=255)),
                ('template', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'signatures',
            },
        ),
    ]
